services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbit1234

  configsvr:
    image: mongo:7
    container_name: configsvr
    hostname: configsvr
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - configsvr_data:/data/db

  shard1:
    image: mongo:7
    container_name: shard1
    hostname: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:7
    container_name: shard2
    hostname: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - shard2_data:/data/db

  mongos:
    image: mongo:7
    container_name: mongos
    hostname: mongos
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2

  mongo-init:
    image: mongo:7
    container_name: mongo-init
    depends_on:
      - configsvr
      - shard1
      - shard2
      - mongos
    volumes:
      - ./scripts/init-sharding.sh:/init-sharding.sh:ro
    entrypoint: ["bash", "/init-sharding.sh"]
    restart: "no"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully

  worker1:
    build: ./worker
    container_name: worker1
    depends_on:
      rabbitmq:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully

  worker2:
    build: ./worker
    container_name: worker2
    depends_on:
      rabbitmq:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully

  forwarder:
    build: ./forwarder
    container_name: forwarder
    stdin_open: true
    tty: true
    depends_on:
      - gateway

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:
